### ISSUE TITLE
DUI70 Crash

### ISSUE THREAD

**Issue by EndlessLuck** [wiktorwiktor12/ConsoleLogonHook#1]
The crash in the attachments occur whenever a button is clicked on the DUI CTRL+ALT+DEL screen.
![Ekran Alıntısı](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/64068157/3afd4f2a-2204-4f93-a65e-217ba2189fc3)

**Comment by windowsxp3790** [comment]
> The crash in the attachments occur whenever a button is clicked on the DUI CTRL+ALT+DEL screen. ![Ekran Alıntısı](https://private-user-images.githubusercontent.com/64068157/341918400-3afd4f2a-2204-4f93-a65e-217ba2189fc3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMjA5ODMsIm5iZiI6MTcxOTAyMDY4MywicGF0aCI6Ii82NDA2ODE1Ny8zNDE5MTg0MDAtM2FmZDRmMmEtMjIwNC00ZjkzLWE2NWUtMjE3YmEyMTg5ZmMzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDAxNDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMTU3OGNhNWE1NzlmZTgxNWNmM2I1NjE1NzlhNDM3YjBmMDViMjU1ZWY4NDcxZTQ3YjcwYzg4ZWJmMzRjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jjRwlZNgfuvFvw7YH-s_UjY4KVkvFMO5gbxORkwfsOM)

Does this happen with en-US too? If not then it might possibly be a issue with translation

**Comment by windowsxp3790** [comment]
![Capture](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/149018134/0791ceed-1124-4947-b4c7-e301f4e344c2)
i was able to reproduce it

**Comment by wiktorwiktor12** [comment]
fixed in 1.0.4a
