### ISSUE TITLE
custom logon screen won't work and ctrl+alt+del screen throws "failure to display security and shut down options" error at me

### ISSUE THREAD

**Issue by kwan-vini** [wiktorwiktor12/ConsoleLogonHook#10]
custom logon throws "not ready" error and freaks out when i try to log in
ctrl+alt+del screen throws "failure to display security and shut down options" error

i disabled lockscreen and i am not using a microsoft acc

what i did to install it (release 1.0.4a)

pasted the 2 .dll files into system32 (consolelogonhook and consolelogonui)
copied au7hui.dll from the release folder and pasted into system32
opened cmd as trustedinstaller with winaerotweaker
pasted and entered each command
took ownership of windows.ui.logon.dll with winaerotweaker and renamed it to have the ".bak" in the end of it

**Comment by wiktorwiktor12** [comment]
not ready being thrown is shown when dui initialization has failed or is taking too long, have you edited dui70.dll or done anything to it?

**Comment by kwan-vini** [comment]
> not ready being thrown is shown when dui initialization has failed or is taking too long, have you edited dui70.dll or done anything to it?

nope, didn't do anything to it. and my windows 10 install is basically fresh, didn't modify it at all.

**Comment by wiktorwiktor12** [comment]
please test latest update

**Comment by kwan-vini** [comment]
> please test latest update

works flawlessly, tysm
