### ISSUE TITLE
Will ConsoleLogonHook get support for windows 11 builds in a future?

### ISSUE THREAD

**Issue by milesprower2293** [wiktorwiktor12/ConsoleLogonHook#15]
Will this have support for windows 11 22H2/23H2 in a future release?

**Comment by wiktorwiktor12** [comment]
Windows 11 should be already supported, just haven't tested it yet

**Comment by milesprower2293** [comment]
> Windows 11 should be already supported, just haven't tested it yet

From what i tried, the Windows 7 login screen tries to load but it enters on a crash loop or in other cases it shows some error messages 

Tried on Windows 11 Version 23H2 Build 22631.3737

**Comment by wiktorwiktor12** [comment]
did u try latest version?

**Comment by wiktorwiktor12** [comment]
send me ur consolelogon.dll as well if latest version doesn't work, and ill try diagnose

**Comment by milesprower2293** [comment]
[ConsoleLogon.zip](https://github.com/user-attachments/files/16047384/ConsoleLogon.zip)

**Comment by milesprower2293** [comment]
> did u try latest version?

yes

**Comment by Hazuki-san** [comment]
It didn't even work for me at all...

**Comment by milesprower2293** [comment]
> It didn't even work for me at all...
> ![image](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/27200811/54242bec-1752-4ccb-bb69-92be2628a8ac)
> 

You forgot to rename windows.ui.logon.dll
But i don't recommend you using consolelogonhook on 11 because it is not compatible

**Comment by Hazuki-san** [comment]
Damn, that's a shame... But hopefully soon enough!

**Comment by wiktorwiktor12** [comment]
For now, you should be fine with replacing consolelogon.dll from release 1.0.2 to use it on windows 11, in the future i will fix the support for it, tho its not a high priority

**Comment by milesprower2293** [comment]
> For now, you should be fine with replacing consolelogon.dll from release 1.0.2 to use it on windows 11, in the future i will fix the support for it, tho its not a high priority

that workaround has the same result so it is not recommended either

https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/131640765/a90a583e-c538-46e3-b98b-addac16ec365

**Comment by wiktorwiktor12** [comment]
then the issue is likely on your end, i could be wrong, need to do testing,
ill do it soon

**Comment by Hazuki-san** [comment]
> > For now, you should be fine with replacing consolelogon.dll from release 1.0.2 to use it on windows 11, in the future i will fix the support for it, tho its not a high priority
> 
> that workaround has the same result so it is not recommended either
> 
>  bandicam.2024-07-02.18-58-55-815.mp4

Can confirm i have the same problem.

**Comment by Hazuki-san** [comment]
Huh, really? Well, don't mind if I do download that then!

**Comment by TheDolphinSlayer** [comment]
DO NOT use this, what i'm explaining is there are things that work, but its not functional, you cannot login, you can't log out. If you do this you'll have to go to Windows RE and restore Windows.UI.Login.dll to log in again

________________________________

**Comment by TheDolphinSlayer** [comment]
> It has to be some minor thing messed up, I mean everything works on windows 11, it seems like its just the user view that's messed up, I can stil call the ease of access menu, shut down, I can use ctrl alt delete to get the security options. And the update/restart screens APPEAR to be working. I know its not a priority right now, I just don't understand any of this lol ![{BBE81F8F-4B1E-4E05-809D-EE8CBD3439AE}](https://private-user-images.githubusercontent.com/73983610/400988954-e404014c-f754-4011-8e28-ebaf8ad34929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDcwNjksIm5iZiI6MTczNjMwNjc2OSwicGF0aCI6Ii83Mzk4MzYxMC80MDA5ODg5NTQtZTQwNDAxNGMtZjc1NC00MDExLThlMjgtZWJhZjhhZDM0OTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDAzMjYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOGZhODk3YzgzM2IwZjUwYWM4YjY1M2Y2OTBkZTAwNGIyNzhlNTEzOGMwODZiODRiNDMzYjVjYTMxOGU3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f1oFivDxnZ2Pp8sC7tuRzNSerilbedq9Sb4K-Wfdibo)
> 
> The console login from 1.0.2 does work(using 23H2), maybe one of the api dlls were changed around, its hard to say tbh

![{73670438-B72A-4A2A-85E6-F534F7046770}](https://github.com/user-attachments/assets/ed723580-0ee9-4609-855e-08e4fb48ea5f)
like I said updating still works lol

**Comment by Hazuki-san** [comment]
still, it's probably because of offset finder update thing.
