### ISSUE TITLE
NVDisplay.Container.exe (Nvidia) crash on "Switch User"

### ISSUE THREAD

**Issue by CatmanFan** [wiktorwiktor12/ConsoleLogonHook#16]
When clicking the "Switch user" option (either on the logon screen or from the Start menu) during a user session, the NVIDIA Container app continues to crash, even after the remaining ones have been fixed. The error is displayed again after logging back on. My desktop has an NVIDIA GPU and driver software installed, which apparently still doesn't seem to handle the hook software properly yet.
The error displayed is shown below:
![error](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/30674270/1ddceddf-d541-4a87-8770-73bdb93b08f9)

**Comment by wiktorwiktor12** [comment]
thats weird, never had that happen, try updating the drivers or downgrading them

**Comment by CatmanFan** [comment]
I have just updated my Nvidia driver to version 556.12 (27 June 2024), and the error message apparently resolved itself as it no longer shows.

The previous driver version with the error message was version 537.42 (21 September 2023). Closing for now since I think this issue can be considered resolved
