### ISSUE TITLE
Tabbing through the field and buttons is buggy

### ISSUE THREAD

**Issue by DaicaQuang** [wiktorwiktor12/ConsoleLogonHook#17]
When using tab to go through the password field and buttons, everything becomes buggy.
The buttons are not clickable nor is pressing enter working to log in. 

The workaround is to press the "Switch User" button and then everything works normally again.

Also, when booting up the system for the first time there is a minor inconvenience in comparison to W7.
In W7 the password field is selected by default when booting up, but the ConsoleLogonHook does not do that yet, so I tried using tab to switch to the password field and then I noticed the bug. 

I'm on W10 22H2 Build 19045.3693 using ConsoleLogonHook v1.0.5

Keep up the great work! This is really awesome and I would love to see more functionality being added later 👍

**Comment by wiktorwiktor12** [comment]
closing as duplicate
