### ISSUE TITLE
White logon screen

### ISSUE THREAD

**Issue by Mrk20200** [wiktorwiktor12/ConsoleLogonHook#23]
All of the graphics (except for the branding, accessibility options, shutdown, and shutdown options icons) are white.
This issue persisted through a restart, and the ConsoleLogonHook.dll, ConsoleLogonUI.dll, and ConsoleLogonHookOffsetCache.txt files are still in the System32 folder.

### Screenshots
Security options:
![screen](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/157867907/bdaa1764-214b-4057-9a05-498955084e36)

Logon screen (username censored with black bar):
![screen2-censored](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/157867907/dca7a1e1-afd8-47da-9973-cb1420680a66)

**Comment by wiktorwiktor12** [comment]
You are likely using the uxtheme patch windhawk mod, add logonui.exe to the exclusions list in windhawk

**Comment by Mrk20200** [comment]
That was the problem, thanks!
