### ISSUE TITLE
2 small bugs with display scaling (125% scaling)

### ISSUE THREAD

**Issue by thecg19** [wiktorwiktor12/ConsoleLogonHook#3]
The branding and buttons at the bottom are a little pixelated. (ignore the windows 10 branding i was messing around with it, it's still pixelated with the normal branding)
![Windows 10 x64-2024-06-22-09-33-31](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/56488032/b8717d28-2d01-4be7-8cdc-2f65ce5af641)

The loading spinner doesn't show at all
![Windows 10 x64-2024-06-22-09-34-01](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/56488032/f374ea70-7d4f-4125-8f79-ba923133ca44)

**Comment by wiktorwiktor12** [comment]
yeah i need to make it load the higher dpi images when scaling is used, this will be done soon, for now this will stay open as a reminder
windows 7 logon screen does this in c++ instead of the ui file, so i will just reference that

**Comment by wiktorwiktor12** [comment]
fixed as of latest update
