### ISSUE TITLE
[REQUEST] Possible to support 32 Bit systems?

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [wiktorwiktor12/ConsoleLogonHook#42]
Tried to install this on a 32 bit Windows 10 LTSC x86 and it broke. It goes black screen. Fortunately I have a restore point. It is possible to support 32 bit systems? Thanks.

**Comment by wiktorwiktor12** [comment]
In theory, it should be doable, but I personally don't see the value in so, if you are able to run windows 10, chances are you can run the 64 bit version of windows 10. I personally don't see the value in spending time working on a 32 bit version of CLH and then maintaining it with any future updates. However, you are more than welcome to port CLH to 32bit if you wish so.
