### ISSUE TITLE
Just a question about the customization

### ISSUE THREAD

**Issue by MochiVoide** [wiktorwiktor12/ConsoleLogonHook#45]
There is a way to change the background wallpaper? Or I have to change the DLL files to change the image?

**Comment by wiktorwiktor12** [comment]
you can use any windows 7 logon screen background changer software

**Comment by MochiVoide** [comment]
> você pode usar qualquer software de troca de plano de fundo da tela de logon do Windows 7

Obrigado!

**Comment by MochiVoide** [comment]
> você pode usar qualquer software de troca de plano de fundo da tela de logon do Windows 7

But, I need some help here, the software programs that I know are not available for download anymore, do you know some and send me the file or download link?
