### ISSUE TITLE
Black screen after installing latest release v1.0.3

### ISSUE THREAD

**Issue by RadicalRMadillo** [wiktorwiktor12/ConsoleLogonHook#5]
I decided to update to the latest release but upon installation I get stuck in a black screen and there's no way to log back on to desktop, even a fresh install of ConsoleLogonHook does the same. My cursor indicates that it's loading yet it's still stuck in a black screen.

**Comment by konstidog** [comment]
Same experience on my end. Had to unrename Windows.UI.Logon.dll to get back to desktop.

**Comment by wiktorwiktor12** [comment]
what version of windows are you running?

**Comment by RadicalRMadillo** [comment]
Currently on Windows 10 21H2 on my machine

**Comment by AsumiLuna** [comment]
Same here on 10 iot ltsc  21H2. Last release was the last version that was able to run on my system.

**Comment by konstidog** [comment]
10 22H2 on my end (19045.4170). 1.0.2 works fine for me both on this install and a 21H2 IoT VM.

**Comment by Erizur** [comment]
Update on the situation:
- It appears that having SecureUXTheme enabled with the "Hook LogonUI" option enabled can cause this issue. Make sure you disable this option and test again.

**Comment by RadicalRMadillo** [comment]
Just checked mine, it doesn't have the Hook LogonUI option enabled and neither do I have SecureUXTheme enabled so it appears that's not the primary cause of the issue.

**Comment by wiktorwiktor12** [comment]
Please check if the latest release fixes your issue
https://github.com/wiktorwiktor12/ConsoleLogonHook/releases/tag/v1.0.4

**Comment by RadicalRMadillo** [comment]
It fixed the black screen issue for me but it seems to be crashing repeatedly since the login pops up and disappears, the welcome text doesn’t show up either.

**Comment by wiktorwiktor12** [comment]
i believe i know the cause, i accidentally reverted something, will fix

**Comment by wiktorwiktor12** [comment]
Please try the latest release

**Comment by RadicalRMadillo** [comment]
Just tried the latest release, so far the issue remains only this time the login popping up and disappearing is faster than before. Still no welcome screen either.

**Comment by wiktorwiktor12** [comment]
Can you send the log file in system32/logs/clh.log

**Comment by RadicalRMadillo** [comment]
[CLH.log](https://github.com/user-attachments/files/16040361/CLH.log)
Here ya go!

**Comment by wiktorwiktor12** [comment]
ok so i see it is crashing, likely a pattern broke, could you send me the consolelogon.dll that your system is using?

**Comment by RadicalRMadillo** [comment]
Sure! here it is. 
[ConsoleLogon.zip](https://github.com/user-attachments/files/16040824/ConsoleLogon.zip)

**Comment by wiktorwiktor12** [comment]
I believe I have identified the issue, fix will be released soon.

**Comment by RadicalRMadillo** [comment]
Alright!

**Comment by RadicalRMadillo** [comment]
The latest release fixed absolutely everything! Thank you so much! I'll be sure to report of any bugs/issues in future releases.
