### ISSUE TITLE
Logon Screen repeatedly crashes(?) on version 1.0.4

### ISSUE THREAD

**Issue by Mrk20200** [wiktorwiktor12/ConsoleLogonHook#9]
The custom logon screen repeatedly shows then hides with no way to escape (without forcefully powering off). The Control-Alt-Delete/Security options screen also displays the "Failure to display security and shut down options" dialog after the screen is shown.
I did not have this problem on version 1.0.3 (even with SecureUxTheme).

**Comment by RadicalRMadillo** [comment]
Same issue here! Also using the login screen with revert8plus which doesn't seem to use SecureUXTheme from what I know.

**Comment by wiktorwiktor12** [comment]
Please try the latest release

**Comment by Mrk20200** [comment]
On version 1.0.4a, the Security Options screen still shows the "Failure to display..." dialog (after the logon screen flashes on screen). When I tried to restart, an error saying "not ready" appeared, pausing the shutdown until I closed it. The logon screen still crashes repeatedly (sometimes showing the "not ready" error)

**Comment by wiktorwiktor12** [comment]
i believe i know the cause, it should be fixed next release

**Comment by amykatname** [comment]
thanks for the release, just reinstalled Windows so I'll try!

**Comment by amykatname** [comment]
Fixed absolutely everything! Thanks a bunch :)

**Comment by Mrk20200** [comment]
It works now! Thank you :)
